MethodologyProject/Meth_Portal/Controllers/AdminController.cs
using Meth_Data.Database;
using Meth_Portal.implemented;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meth_Portal.Controllers
{
    public class AdminController : Controller
    {
        studentOperations student_operation = new studentOperations();
        AdminOperation admin_operation = new AdminOperation();
        // GET: Admin
        public ActionResult Index()
        {
            List<StudentCours> result = student_operation.GetAllStudentCourses(0);
            if (result == null)
            {
                result = new List<StudentCours>();
            }
            return View(result);
        }
       
        public ActionResult Main()
        {

            return View();
        } 

        [HttpGet]
        public ActionResult EditCourse(int Id)
        {
            StudentCours result = student_operation.GetStudentCourseById(Id);
            return View(result);
        }
        [HttpPost]
        public ActionResult EditCourse(StudentCours result)
        {
            student_operation.EditStudentCourse(result);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult DeleteCourse(int Id)
        {

            StudentCours result = student_operation.GetStudentCourseById(Id);
            return View(result);
        }
        [HttpPost]
        public ActionResult DeleteCourse(StudentCours val)
        {
            try
            {
                student_operation.DeleteStudentCourse(val);
            }
            catch (Exception)
            {

                return View(val);
            }


            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult lookforStudentCourses()
        {

            return View();
        }
        [HttpPost]
        public ActionResult lookforStudentCourses(int Search_val)
        {

            List<StudentCours> result = student_operation.GetAllStudentCourses(Search_val);
            if (result == null)
            {
                result = new List<StudentCours>();
            }
            return View("Index",result);
        }

        public ActionResult StudentList()
        {
            List<StudentInfo> result= admin_operation.GetAllStudents();
            return View(result);
        }
    }
}

MethodologyProject/Meth_Portal/Controllers/CourseController.cs
using Meth_Data.Database;
using Meth_Portal.implemented;
using Meth_Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meth_Portal.Controllers
{
    
    public class CourseController : Controller
    {
        private courseOperations operation =new courseOperations();
        public CourseController ()
        {
        }
        
        // GET: course
        public ActionResult Index()
        {
            List<Course> list=operation.GetAllCourses();
            
            return View(list);
        }

        // GET: course/Details/5
        public ActionResult Details(int id)
        {
            Course Result = operation.GetCourseById(id);
            return View(Result);
        }

        // GET: course/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: course/Create
        [HttpPost]
        public ActionResult Create(Course collection)
        {
            try
            {
                // TODO: Add insert logic here
              int result=  operation.AddCourse(collection);
                


                return RedirectToAction("Index");
            }
            catch(Exception e )
            {
                return View(collection);
            }
        }

        // GET: course/Edit/5
        public ActionResult Edit(int id)
        {
            Course Result = operation.GetCourseById(id);
            return View(Result);
        }

        // POST: course/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Course collection)
        {
            try
            {
                // TODO: Add update logic here
                operation.UpdateCourse(collection);
                return RedirectToAction("Index");

            }
            catch
            {
                return View(collection);
            }
        }

        // GET: course/Delete/5
        public ActionResult Delete(int id)
        {
            Course result = operation.GetCourseById(id);
            return View(result);
        }

        // POST: course/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Course collection)
        {
            try
            {

                // TODO: Add delete logic here
                operation.DeleteCourse(collection);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(collection);
            }
        }
    }
}

MethodologyProject/Meth_Portal/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href=@Url.Content("~/Content/assets/img/apple-icon.png")>
    <link rel="icon" type="image/png" href=@Url.Content("~/Content/assets/img/favicon.png")>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href=@Url.Content("~/Content/assets/css/bootstrap.min.css") rel="stylesheet" />
    <link href=@Url.Content("~/Content/assets/css/now-ui-dashboard.css?v=1.0.1") rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
   
</head>
<body class="">
    <div class="wrapper ">

        <div class="sidebar" data-color="orange">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
            -->
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text logo-mini">
                    CT
                </a>
                <a href="http://www.creative-tim.com" class="simple-text logo-normal">
                    Creative Tim
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav" id="myTab">
                    <li >
                        <a href="@Url.Action("Index","Admin")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li >
                        <a href="@Url.Action("Index","Course")">
                            <i class="now-ui-icons design_app"></i>
                            <p>courses</p>
                        </a>
                    </li>
                   
                    <li>
                        <a href="@Url.Action("lookforStudentCourses","Admin")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Look for student courses</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("StudentList","Admin")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Student List</p>
                        </a>
                    </li>
                   
                </ul>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg  navbar-absolute bg-dark fixed-top">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="">Dashboard</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <form>
                        <div class="input-group no-border">
                            <input type="text" value="" class="form-control" placeholder="Search...">
                            <span class="input-group-addon">
                                <i class="now-ui-icons ui-1_zoom-bold"></i>
                            </span>
                        </div>
                    </form>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#pablo">
                                <i class="now-ui-icons media-2_sound-wave"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Stats</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="now-ui-icons location_world"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Some Actions</span>
                                </p>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#pablo">
                                <i class="now-ui-icons users_single-02"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Account</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="main-panel" style="padding-left:30px">
           @RenderBody()
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <nav>
                    <ul>
                        <li>
                            <a href="https://www.creative-tim.com">
                                Creative Tim
                            </a>
                        </li>
                        <li>
                            <a href="http://presentation.creative-tim.com">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="http://blog.creative-tim.com">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                    &copy;
                    <script>
                            document.write(new Date().getFullYear())
                    </script>, Designed by
                    <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
                    <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
                </div>
            </div>
        </footer>
    </div>

   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>


<!--   Core JS Files   -->
<script src=@Url.Content("~/Content/assets/js/core/jquery.min.js")></script>
<script src=@Url.Content("~/Content/assets/js/core/popper.min.js")></script>
<script src=@Url.Content("~/Content/assets/js/core/bootstrap.min.js")></script>
<script src=@Url.Content("~/Content/assets/js/plugins/perfect-scrollbar.jquery.min.js")></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src=@Url.Content("~/Content/assets/js/plugins/chartjs.min.js")></script>
<!--  Notifications Plugin    -->
<script src=@Url.Content("~/Content/assets/js/plugins/bootstrap-notify.js")></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src=@Url.Content("~/Content/assets/js/now-ui-dashboard.js?v=1.0.1")></script>
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<script src=@Url.Content("~/Content/assets/demo/demo.js")></script>
<script>
   
    $(document).ready(function () {

        //$("li").click(function () {
        //    // If this isn't already active
        //    if (!$(this).hasClass("active")) {
        //        // Remove the class from anything that is active
        //        $("li.active").removeClass("active");
        //        // And make this active
        //        $(this).addClass("active");
        //    }
        //});


        $('li > a').click(function () {
            $('li').removeClass();
            $(this).parent().addClass('active');
        });
        // Javascript method's body can be found in assets/js/demos.js
       demo.initDashboardPageCharts();
    });
</script>
</html>

MethodologyProject/Meth_Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href=@Url.Content("~/Content/assets/img/apple-icon.png")>
    <link rel="icon" type="image/png" href=@Url.Content("~/Content/assets/img/favicon.png")>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href=@Url.Content("~/Content/assets/css/bootstrap.min.css") rel="stylesheet" />
    <link href=@Url.Content("~/Content/assets/css/now-ui-dashboard.css?v=1.0.1") rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
   
</head>
<body class="">
    <div class="wrapper ">

        <div class="sidebar" data-color="orange">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
            -->
            <div class="logo">
                <a href="" class="simple-text logo-mini">
                    CT
                </a>
                <a href="" class="simple-text logo-normal">
                    Creative Tim
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav" id="myTab">
                    <li >
                        <a href="@Url.Action("Index","Home")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("RegisteCourse","Home")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Register Course</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("StudentTimeTable","Home")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Student Courses Time Table </p>
                        </a>
                    </li>
                    

                </ul>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg  navbar-absolute bg-dark fixed-top" >
            <div class="container-fluid" >
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="">Dashboard</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <form>
                        <div class="input-group no-border">
                            <input type="text" value="" class="form-control" placeholder="Search...">
                            <span class="input-group-addon">
                                <i class="now-ui-icons ui-1_zoom-bold"></i>
                            </span>
                        </div>
                    </form>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#pablo">
                                <i class="now-ui-icons media-2_sound-wave"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Stats</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="now-ui-icons location_world"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Some Actions</span>
                                </p>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#pablo">
                                <i class="now-ui-icons users_single-02"></i>
                                <p>
                                    <span class="d-lg-none d-md-block">Account</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="main-panel">
           @RenderBody()
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <nav>
                    <ul>
                        <li>
                            <a href="https://www.creative-tim.com">
                                Creative Tim
                            </a>
                        </li>
                        <li>
                            <a href="http://presentation.creative-tim.com">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="http://blog.creative-tim.com">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                    &copy;
                    <script>
                            document.write(new Date().getFullYear())
                    </script>, Designed by
                    <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
                    <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
                </div>
            </div>
        </footer>
    </div>

   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/js/required")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>


</html>
<!--   Core JS Files   -->
<script src=@Url.Content("~/Content/assets/js/core/jquery.min.js")></script>
<script src=@Url.Content("~/Content/assets/js/core/popper.min.js")></script>
<script src=@Url.Content("~/Content/assets/js/core/bootstrap.min.js")></script>
<script src=@Url.Content("~/Content/assets/js/plugins/perfect-scrollbar.jquery.min.js")></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src=@Url.Content("~/Content/assets/js/plugins/chartjs.min.js")></script>
<!--  Notifications Plugin    -->
<script src=@Url.Content("~/Content/assets/js/plugins/bootstrap-notify.js")></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src=@Url.Content("~/Content/assets/js/now-ui-dashboard.js?v=1.0.1")></script>
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<script src=@Url.Content("~/Content/assets/demo/demo.js")></script>
<script>

    $(document).ready(function () {

        //$("li").click(function () {
        //    // If this isn't already active
        //    if (!$(this).hasClass("active")) {
        //        // Remove the class from anything that is active
        //        $("li.active").removeClass("active");
        //        // And make this active
        //        $(this).addClass("active");
        //    }
        //});


        $('li > a').click(function () {
            $('li').removeClass();
            $(this).parent().addClass('active');
        });
        // Javascript method's body can be found in assets/js/demos.js
    });
</script>